### ISSUE TITLE
bindle create-key requires bindle server to be running

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/bindle#187] opened 2021-07-23 19:02 UTC
This seems to be a bit of a chicken-and-egg problem... The CLI requires a running bindle server to generate a keypair. But you need a keypair to run bindle-server.

```
$ bindle create-key 'Matt Fisher <matt.fisher@microsoft.com>'
error: The following required arguments were not provided:
    --server <server-url>

USAGE:
    bindle [OPTIONS] --server <server-url> <SUBCOMMAND>

For more information try --help
```

**Comment by bacongobbler** [comment] 2021-07-23 19:06
Workaround is to provide a garbage input parameter to `--server`:

```
$ bindle --server http://localhost create-key --secrets-file foo.toml 'Matt Fisher <matt.fisher@microsoft.com>'
Writing keys to foo.txt
File foo.txt does not exist. Creating it.
```

**Comment by thomastaylor312** [comment] 2021-07-26 17:46
Closing as duplicate of #111

**Closed by thomastaylor312** 2021-07-26 17:46 UTC
