### ISSUE TITLE
`bindle create-key` creates TOML file with 0700 (executable) permissions

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/bindle#192] opened 2021-07-26 16:38 UTC
The secret_keys.toml file generated by `bindle create-key` should have 0600 permissions (RW only) rather than RWX.

**Comment by technosophos** [comment] 2021-07-29 03:24
Is this a duplicate of #176 or a report that #115 was not correctly fixed?

**Comment by bacongobbler** [comment] 2021-08-10 20:42
#115 fixes part of the issue by making the file with read-write-execute permissions. However, keyring.toml is not executable, therefore it should be written with 0600 (read-write) permissions.

Current behaviour:

```
$ sudo bindle --server 'http://foo.com' create-key 'Matt Fisher <matt.fisher@microsoft.com>' -f keyring.toml
Writing keys to keyring.toml
File keyring.toml does not exist. Creating it.
$ ll
total 16
drwxr-xr-x  2 root root 4096 Aug 10 20:39 ./
drwxr-xr-x 99 root root 4096 Aug 10 20:25 ../
-rw-r--r--  1 root root  217 Aug 10 20:32 config.toml
-rwx------  1 root root  196 Aug 10 20:39 keyring.toml*
```

**Comment by nitishm** [comment] 2021-08-11 22:29
I would love to contribute. Fair warning: I am still learning Rust so I dont have much production experience writing Rust code.
Correct me if I am wrong, but from what I gather it seems like this block needs to change. Specifically the `save_file()` that needs addressing

https://github.com/deislabs/bindle/blob/219d98dd3dd88e34635523506fe927758ad38c49/bin/client/main.rs#L224-L236

**Comment by bacongobbler** [comment] 2021-08-11 22:32
Yeah, pretty close. Here's the place that needs changing:

https://github.com/deislabs/bindle/blob/219d98dd3dd88e34635523506fe927758ad38c49/src/invoice/signature.rs#L346

**Comment by nitishm** [comment] 2021-08-11 22:44
> Yeah, pretty close. Here's the place that needs changing:
> 
> https://github.com/deislabs/bindle/blob/219d98dd3dd88e34635523506fe927758ad38c49/src/invoice/signature.rs#L346

Awesome - let me create a PR for this

**Closed** 2021-08-12 19:48 UTC
Labels: bug, good first issue
